[tool.poetry]
name = "pullman"
version = "0.8"
description = "ðŸ¥ž Manage ghstack pull requests ðŸ¥ž"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.scripts]
pullman = "pullman:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
